schema-version: v2
kind: plugin
metadata:
  name: spring-base-template
  display-name: spring-base-template
  description: Spring base template
  version: 0.0.6
  picture: plugin.png
spec:
  type: app
  compatibility:
    - kotlin
    - maven
    - spring
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.6.md
  requirements: docs/requirements.md
  single-use: true
  repository: https://github.com/leodelmiro/stackspot-spring-base-template
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Kotlin
    - Maven
    - Spring Boot
  stk-projects-only: false
  inputs:
    - label: Type application name
      name: project_name
      type: text
      required: true
      default: Spring Base Project
      help: 'Inform your application name (e.g.: Spring Base Project)'
    - label: Type description
      name: description
      type: text
      required: false
      default: Demo project for Stackspot
      help: 'Inform project description (e.g.: Demo project for Stackspot)'
    - label: Type artifact Id
      name: artifact_id
      type: text
      required: true
      default: spring-base-project
      help: 'Inform your artifact id (e.g.: spring-base-project)'
    - label: Type group name
      name: group_name
      type: text
      required: true
      default: br.com.leodelmiro
      help: 'Inform your group name (e.g.: br.com.leodelmiro)'
  global-computed-inputs:
    main_class: "{{ project_name | pascalcase }}"
    project_name_lower: "{{ artifact_id | replace('-','') | replace('_','') | lower }}"